# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c67aab6cc14a7e3ec513b3bef71dc8dc7a6eaff3d8528992696d4a25d35acba6444cf1ee0c8f509c740cbd57760616a06e34cf43f1910452b87f7a23c7303473

test:
  secret_key_base: ed76f7934c2c301a7a806e1449bfffbc6a818c469254248b13211d03b6c994bd125448d6769d72826267c9dbca4122e8d72963987203649d8cb2c326ad2149ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
